### ISSUE TITLE
number_chars(N,"0'\w"). panic

### ISSUE THREAD

**Issue by UWN** [ichiban/prolog#207]
```
?- number_chars(N,"0'\w").
false.panic: runtime error: index out of range [119] with length 119

goroutine 8 [running]:
github.com/ichiban/prolog/engine.(*Lexer).integerCharEscape(0xc00012ec00?, 0xc000087200)
	/opt/gupu/ichiban-prolog/engine/lexer.go:568 +0xbb
github.com/ichiban/prolog/engine.(*Lexer).integerChar(0xc000087200?, 0xc000087200)
	/opt/gupu/ichiban-prolog/engine/lexer.go:541 +0x8c
github.com/ichiban/prolog/engine.(*Lexer).integerZero(0xc00012ec00, 0xc000087200)
	/opt/gupu/ichiban-prolog/engine/lexer.go:483 +0x154
github.com/ichiban/prolog/engine.(*Lexer).Token(0xc00012ec00)
	/opt/gupu/ichiban-prolog/engine/lexer.go:150 +0x135
github.com/ichiban/prolog/engine.(*Parser).expect(0xc000100310, 0x11, {0x0, 0x0, 0x0})
	/opt/gupu/ichiban-prolog/engine/parser.go:188 +0x5c
github.com/ichiban/prolog/engine.(*Parser).accept(0xc000100310, 0x80?, {0x0?, 0x203000?, 0x203000?})
	/opt/gupu/ichiban-prolog/engine/parser.go:107 +0x2d
github.com/ichiban/prolog/engine.(*Parser).number(0xc00010b001?)
	/opt/gupu/ichiban-prolog/engine/parser.go:267 +0x45
github.com/ichiban/prolog/engine.(*Parser).Number(0xc000076840?)
	/opt/gupu/ichiban-prolog/engine/parser.go:257 +0x1e
github.com/ichiban/prolog/engine.NumberChars({0x591540?, 0xc0003f91f0}, {0x5913c0?, 0xc0000adec0}, 0xc00000c2b8, 0xc00012e940)
	/opt/gupu/ichiban-prolog/engine/builtin.go:2209 +0x9cc
github.com/ichiban/prolog/engine.predicate2.Call(0xc?, 0xc000110120?, {0xc000087120?, 0x534fe0?, 0xc00005e240?}, 0xc000087120?, 0xc000095eb8?)
	/opt/gupu/ichiban-prolog/engine/vm.go:413 +0xec
github.com/ichiban/prolog/engine.(*VM).Arrive.func2({0x4b21ca, 0xc0003f81a0})
	/opt/gupu/ichiban-prolog/engine/vm.go:182 +0x3a
github.com/ichiban/prolog/engine.(*Promise).child(0xc00012ad70, {0x5916e8?, 0xc00027e2c0?})
	/opt/gupu/ichiban-prolog/engine/promise.go:108 +0x45
github.com/ichiban/prolog/engine.(*Promise).Force(0xc00012a5f0, {0x5916e8, 0xc00027e2c0})
	/opt/gupu/ichiban-prolog/engine/promise.go:100 +0x15f
github.com/ichiban/prolog.(*Interpreter).QueryContext.func1()
	/opt/gupu/ichiban-prolog/interpreter.go:201 +0x155
created by github.com/ichiban/prolog.(*Interpreter).QueryContext
	/opt/gupu/ichiban-prolog/interpreter.go:193 +0x3bd
exit status 2
```

**Comment by ichiban** [comment]
@UWN After redoing the parser/lexer in `v0.10.0`, it's a syntax error now. Was it an expected behavior?

```console
$ $(go env GOPATH)/bin/1pl
Top level for ichiban/prolog v0.10.0
This is for testing purposes only!
See https://github.com/ichiban/prolog for more details.
Type Ctrl-C or 'halt.' to exit.
?- number_chars(N,"0'\w").
2022/07/16 11:59:36 failed to query: unexpected token: {invalid "0'\w}
```

**Comment by UWN** [comment]
Both errors are perfect:

```
?- catch(number_chars(N,"0'\w"),Error,true).
2022/07/16 15:28:55 failed to query: unexpected token: {invalid "0'\w}
?- catch(number_chars(N,['0','''',\,w]),Error,true).     
N = _992,
Error = error(syntax_error('not a number'),number_chars/2).
```
